"""The PROCESS-KNOWLEDGE digest: what has been tried, what worked and what did not, generated from the register.

`knowledge_map.json` files every registered claim under the process INGREDIENTS it is about (siblings, the strategy
tree, augmentation, ...). Each ingredient carries a short conclusion and the claims that conclusion rests on; the
map also lists the trials that were abandoned without a proof. `render` turns the map plus the register's CURRENT
verdicts into docs/process-knowledge.md, so the page cannot drift from the evidence, and `check_map` refuses a map
that leaves a claim unfiled or cites one it does not list."""
from __future__ import annotations

DECIDED = {"supported", "refuted", "inconclusive", "null"}


def check_map(kmap: dict, views: list) -> list:
    """Every reason `kmap` is not a complete, consistent filing of the registered claims in `views`."""
    registered = {v["id"] for v in views}
    problems, filed, keys = [], set(), set()
    for ing in kmap.get("ingredients", []):
        key = ing.get("key")
        if key in keys:
            problems.append(f"ingredient {key} is listed twice")
        keys.add(key)
        if not str(ing.get("conclusion", "")).strip() or not str(ing.get("what", "")).strip():
            problems.append(f"ingredient {key} has no conclusion or description")
        for cid in ing.get("claims", []):
            if cid not in registered:
                problems.append(f"{cid} is not registered (ingredient {key})")
            filed.add(cid)
        for cid in ing.get("based_on", []):
            if cid not in ing.get("claims", []):
                problems.append(f"ingredient {key} cites {cid} without filing it there")
    problems += [f"{cid} is not filed under any ingredient" for cid in sorted(registered - filed)]
    for i, trial in enumerate(kmap.get("unproven_trials", [])):
        if not all(str(trial.get(k, "")).strip() for k in ("what", "lesson", "plan")):
            problems.append(f"unproven trial {i} needs what, lesson and plan")
    return problems


def _status(views_by_id: dict, cid: str) -> str:
    status = views_by_id[cid]["status"]
    return status if status in DECIDED else f"{status} — PENDING"


def render(kmap: dict, views: list) -> str:
    """The digest page, from the map and the register's current verdicts."""
    by_id = {v["id"]: v for v in views}
    counts: dict = {}
    for v in views:
        counts[v["status"]] = counts.get(v["status"], 0) + 1
    lines = ["# Process knowledge — what was tried, what worked, what did not", "",
             "Generated by `examples/boardgames/scripts/knowledge_digest.py` from the claims register "
             "(`examples/boardgames/hypotheses.json`) and `examples/boardgames/knowledge_map.json`. Do not edit by "
             "hand: a test fails when this page is stale or when a registered claim is not filed here.", "",
             f"{len(views)} claims: " + ", ".join(f"{n} {s}" for s, n in sorted(counts.items())) + ".", ""]
    for ing in kmap["ingredients"]:
        lines += [f"## {ing['name']}", "", ing["what"], "", f"**Conclusion.** {ing['conclusion']}", "",
                  "rests on: " + ", ".join(f"{c} ({_status(by_id, c)})" for c in ing["based_on"]), ""]
        lines += [f"- **{c}** {by_id[c]['status'].upper()} — {by_id[c]['claim']}" for c in ing["claims"]]
        lines.append("")
    lines += ["## Abandoned or unproven trials", "",
              "Trials that ended without a registered claim. Each is recorded with its lesson and where the plan "
              "describes it.", ""]
    lines += [f"- {t['what']} **Lesson:** {t['lesson']} ({t['plan']})" for t in kmap.get("unproven_trials", [])]
    return "\n".join(lines) + "\n"
