// Boot config seam (A5). Loaded before boot.js. In the BASE modeltrainer this file is intentionally EMPTY, so
// `window.__TRAINER_BOOT__` stays undefined and the viewer opens as the multi-project HUB — the default.
//
// A project SEEDED from modeltrainer (scripts/seed-single-purpose.mjs) overwrites this file with an assignment
// like `window.__TRAINER_BOOT__ = { mode: 'single', dir: '.', name: '…', manifestRelPath: '…' }`, which makes
// its copy of the viewer boot straight into that one project's dashboard. Generated by
// TrainerBoot.renderBootConfig so it is validated to actually open single before it is written.
